### ISSUE TITLE
Zilliqa

### ISSUE THREAD

**Issue by sniper-noob** [AndreaLanfranchi/neth-proxy#3]
Hi.
Can you make this proxy work with Zilliqa Nodes?

**Comment by AndreaLanfranchi** [comment]
Working on it

**Comment by frode88** [comment]
Thank you.

**Comment by sniper-noob** [comment]
Hi. There is any ETA when we will have opportunity to test it. Thank you. If you need miner or Nodes for Testing I can help you with that.

**Comment by AndreaLanfranchi** [comment]
Hi @frode88 
a tad busy right now. But I think within the end of April

**Comment by frode88** [comment]
Hope you relase it soon and save us:) there is only one Proxy with Share Difficulty (static) and havnt released the code for it.
